name: vue
type: service
from: nginx
fromVersionConstraint: "^1.0.0"
fromVersion: "1.0.15"
title: Nginx (Vue)
labels:
- nginx
- vue

build:
  connect: true
  boilerplates:
  - name: vue
    title: Vue boilerplate
    repo: https://github.com/wodby/vue-boilerplate
    branch: main
